title: Blog of mraffia
author: mraffia
email: mohraffia@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Just mraffia's Blog, really.

# social links
twitter_username: mohraffia # DO NOT include the @ character, or else the build will fail!
github_username:  mraffia # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
